### ISSUE TITLE
Error: did not recognize object of type "ImportExpression"

### ISSUE THREAD

**Issue by dionii1** [forsartis/vue-cli-plugin-tailwind#9]
Hello,
after I select with type of tailwind config file I want (minimal) 
i get this error:  

Invoking generator for vue-cli-plugin-tailwind.
 ERROR  Error: did not recognize object of type "ImportExpression"
Error: did not recognize object of type "ImportExpression"

What should I do?

**Comment by forsartis** [comment]
Sorry, I couldn’t reproduce the error on a Mac or Windows. Perhaps updating node can solve the issue.

**Comment by sodatea** [comment]
You might have a dynamic import expression in `src/index.js`.
It could be caused by this line: https://github.com/forsartis/vue-cli-plugin-tailwind/blob/2cbd88eef79fc238fff286ecfbccfbec7f4de456/generator/index.js#L56

Vue CLI implements the `injectImports` utility with `jscodeshift` and `recast` underlyingly. And there was a bug in `recast` that it failed to print `ImportExpression`. It wasn't fixed until days ago https://github.com/benjamn/recast/commit/aac6d75a61cba70fd161da94e13b7e85a2ee9af6

One solution is to reinstall `@vue/cli` globally in the hope that the transitive `recast` dependency will resolve to the latest version.
If that doesn't work out, comment out the dynamic import expressions in `src/index.js`, run `vue invoke tailwind` or `vue add tailwind`, then uncomment the expressions after the generator runs successfully.

**Comment by sodatea** [comment]
Edit: the `ImportExpression` issue also happens in older versions of `ast-types`.
To force update the 2 transitive dependency versions, you may need to clean the yarn or npm cache first.
